[SEC-4668] Fix Nuget package signing by using a valid certificate fingerprint (#27)
* [SEC-4668] Fix Nuget package signing by using a valid certificate fingerprint. Add test for a nuget package.

* Properly exit job on script failure. Fix path and quote formatting.

* Make exit code check more efficient.

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -25,6 +25,7 @@ runs:
         echo "SM_HOST=${{ env.CERTIFICATE_HOST }}" >> "$GITHUB_ENV"
         echo "SM_API_KEY=${{ env.CERTIFICATE_HOST_API_KEY }}" >> "$GITHUB_ENV"
         echo "SM_CLIENT_CERT_PASSWORD=${{ env.CLIENT_CERTIFICATE_PASSWORD }}" >> "$GITHUB_ENV"
+        echo "SM_CODE_SIGNING_CERT_FINGERPRINT=${{ env.CERTIFICATE_FINGERPRINT }}" >> "$GITHUB_ENV"
         echo "SM_KEYPAIR_ALIAS=${{ env.KEYPAIR_ALIAS }}" >> "$GITHUB_ENV"
         if [ "${{ runner.os }}" == "Windows" ]
         then
@@ -51,7 +52,12 @@ runs:
       env:
         GITHUB_WORKSPACE: ${{ github.workspace }}
       run: |
+        $ErrorActionPreference = 'Stop'
         smctl windows certsync --keypair-alias="${{ env.SM_KEYPAIR_ALIAS }}"
+        if ($LASTEXITCODE -ne 0) {
+          Write-Error "Error: certsync failed with exit code $LASTEXITCODE"
+          exit $LASTEXITCODE
+        }
         $file_path = "${{ env.GITHUB_WORKSPACE }}\${{ inputs.path-to-binary }}"
         $files_to_sign = @()
         if (Test-Path -Path $file_path -PathType Leaf) {
@@ -60,11 +66,29 @@ runs:
         else {
           Get-ChildItem -Path $file_path -File -Recurse
           $files_to_sign = @(Get-ChildItem -Path $file_path -File -Recurse)
-        }        
+        }
         foreach ( $f in $files_to_sign )
         {
-          smctl sign -v --keypair-alias="${{ env.SM_KEYPAIR_ALIAS }}" --input "$($f.FullName)"
+          # check if the file is a Nuget package
+          if ($f.FullName -match '\.nupkg$') {
+            if (-not [string]::IsNullOrWhiteSpace("${{ env.SM_CODE_SIGNING_CERT_FINGERPRINT }}")) {
+              smctl sign -v --fingerprint "${{ env.SM_CODE_SIGNING_CERT_FINGERPRINT }}" --input "$($f.FullName)"
+            } else {
+              Write-Error "SM_CODE_SIGNING_CERT_FINGERPRINT is not set or is empty. Cannot sign .nupkg file: $($f.FullName)"
+              exit 1
+            }
+          } else {
+            smctl sign -v --keypair-alias="${{ env.SM_KEYPAIR_ALIAS }}" --input "$($f.FullName)"
+          }
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Error: Failed to sign $($f.FullName) with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
           smctl sign verify --input "$($f.FullName)"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Error: Failed to verify $($f.FullName) with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
         }
       if: runner.os == 'Windows'
       shell: powershell
