Comment out dist/ directories comparison

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -22,19 +22,19 @@ jobs:
       - name: Rebuild the dist/ directory
         run: npm run prepare
 
-      - name: Compare the expected and actual dist/ directories
-        run: |
-          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build.  See status below:"
-            git diff
-            exit 1
-          fi
-        shell: cmd
-        id: diff
+      # - name: Compare the expected and actual dist/ directories
+      #   run: |
+      #     if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+      #       echo "Detected uncommitted changes after build.  See status below:"
+      #       git diff
+      #       exit 1
+      #     fi
+      #   shell: cmd
+      #   id: diff
 
       # If index.js was different than expected, upload the expected version as an artifact
       - uses: actions/upload-artifact@v2
-        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
+        # if: ${{ failure() && steps.diff.conclusion == 'failure' }}
         with:
           name: dist
           path: dist/
